### ISSUE TITLE
KeyError: "Dataset 'x_train' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, .....

### ISSUE THREAD

**Issue by totoadel** [jinfagang/yolov7#100]
when try to train custom instance segmentation i get this error 

`%cd /content/yolov7
!python  train_inseg.py --config-file '/content/yolov7/configs/balloon/Base-SparseInst.yaml' --num-gpus 1`

`KeyError: "Dataset 'x_train' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"
`

**Comment by jinfagang** [comment]
Please refer `train_customdatasets.py`

**Comment by totoadel** [comment]
@jinfagang i use train_inseg.py to do instance segmentation 
And train_customdatasets.py didn't train for instance segmentation

**Comment by jinfagang** [comment]
@totoadel Please have some common knowledge. in there have code tells you have to register custom dataset......

**Comment by totoadel** [comment]
@jinfagang how to  register custom dataset?
