### ISSUE TITLE
NameError: name 'mask_util' is not defined

### ISSUE THREAD

**Issue by TeodorChiaburu** [jinfagang/yolov7#105]
I receive a syntactic error on the following line:

https://github.com/jinfagang/yolov7/blob/f81243eca48f91821fa1e143d131dd9192397d75/yolov7/data/detection_utils.py#L186

**Comment by jinfagang** [comment]
looks like you are not using standared coco format as training. Try importing mask_util from pycocotools. You can also send me a fix PR is possible.

**Comment by TeodorChiaburu** [comment]
I am encoding the segmentation masks as RLE. I imported `mask `as `mask_util `from `pycocotools `(just like in `detectron2`) and it solved it. Thank you!
