### ISSUE TITLE
SparseInst expecting pred_boxes

### ISSUE THREAD

**Issue by TeodorChiaburu** [jinfagang/yolov7#113]
While trying to train a **SparseInst** on a custom dataset for instance segmentation, I came across the following error:

`AttributeError: Cannot find field 'pred_boxes' in the given Instances!`

The error is thrown from within the `detectron2 `library.
When I print one Instance, there are indeed no `pred_boxes `in there, only `pred_masks`. But as far as I understand, **SparseInst** does not output bounding boxes, it predicts directly seg. masks, as they highlight in their paper: https://arxiv.org/abs/2203.12827
Then I am wondering why the code is looking for predicted boxes in this case... o_0

**Comment by jinfagang** [comment]
@TeodorChiaburu Hi, can u paste the whole traceback start with somewhere broken inside yolov7? If you using `train_inseg` it shouldn't apply gtboxes since sparseinst meta arch doesn't query boxes in training stage.

**Comment by jinfagang** [comment]
looks like happens in evaluation, for evaluation pred_boxes is necessary, can u check the sparseinstseg meta arch outputs predbox or not in Instances?  it should be converted, if not, then we might need some workaround to fix it.

**Comment by TeodorChiaburu** [comment]
Apparently, the SparseInst does not output any predbox in Instances during inference:

```
Start inference on 225 batches
Instances(num_instances=100, image_height=333, image_width=500, fields=[pred_masks: tensor([[[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        ...,

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]]), scores: tensor([0.0314, 0.0281, 0.0777, 0.0230, 0.0239, 0.0335, 0.0331, 0.0284, 0.0584,
        0.0000, 0.2325, 0.2308, 0.0478, 0.0500, 0.0227, 0.0218, 0.0168, 0.0959,
        0.0360, 0.0202, 0.0000, 0.0230, 0.0000, 0.0564, 0.0000, 0.0477, 0.0222,
        0.0267, 0.0322, 0.0252, 0.0430, 0.0298, 0.0316, 0.0623, 0.0493, 0.0210,
        0.0163, 0.0000, 0.0000, 0.0000, 0.0282, 0.0000, 0.0312, 0.0000, 0.0201,
        0.1958, 0.0455, 0.0000, 0.0308, 0.0506, 0.0279, 0.0157, 0.0429, 0.0000,
        0.0000, 0.0265, 0.0880, 0.0650, 0.0722, 0.0322, 0.0350, 0.0000, 0.2292,
        0.0000, 0.0561, 0.0240, 0.0687, 0.0277, 0.0326, 0.0000, 0.0000, 0.0176,
        0.0158, 0.0166, 0.0562, 0.0000, 0.0000, 0.0313, 0.0469, 0.0381, 0.0151,
        0.0489, 0.0704, 0.0000, 0.0276, 0.0262, 0.0209, 0.0300, 0.0291, 0.0248,
        0.0223, 0.0397, 0.0219, 0.0787, 0.0191, 0.0309, 0.0286, 0.0000, 0.0633,
        0.0183]), pred_classes: tensor([ 0, 14, 14, 14, 14, 75, 75, 75, 14,  0, 14, 14, 75, 75, 14, 14,  0, 14,
        75, 14, 75, 75,  0, 14, 75, 75, 75, 14, 14, 14, 14, 14, 75, 14, 14, 14,
         0, 75,  0,  0, 14,  0, 75,  0, 14, 14, 14,  0, 14, 14, 58,  0, 14,  0,
        14, 75, 14, 75, 14,  0,  0,  0, 58, 14, 14,  0, 14,  0, 14, 75,  0,  0,
        14,  0, 14,  0,  0, 75, 14, 75,  0, 75, 58,  0,  0,  0,  0, 14, 14,  0,
        58, 75, 75, 14, 75,  0, 75,  0, 58, 14])])
```

**Comment by jinfagang** [comment]
@TeodorChiaburu  can u have a little try on override trainner as original does? https://github.com/hustvl/SparseInst/blob/main/train_net.py

I believe this can solve the problem, if it can evaluation correct, please send me a PR to fix it.

**Comment by TeodorChiaburu** [comment]
Hi! It took me a whole day, but I think I figured the issue. 

After trying to overwrite the **Trainer** as you suggested, the error still persisted, no matter what **Evaluator** I used: **COCOEvaluator**, **SemSegEvaluator** etc. 

Finally, I found out that there is a slight difference between the `coco_evaluation.py` file from the `detectron2` repo as opposed to the same file from the `SparseInst` repo. Given that **SparseInst** is, as mentioned above, a true/pure segmenter, it does not necessarily predict bounding boxes. So while an **Image Instance** in `detectron2` is always assumed to have an attribute _pred_boxes_, this is not the case for an **Instance** in `SparseInst`. Notice the extra `if has_box` in the `SparseInst` code:

`detectron2`:
https://github.com/facebookresearch/detectron2/blob/48b598b4f61fbb24182a69b521b2a0ba3252b842/detectron2/evaluation/coco_evaluation.py#L407

vs.

`SparseInst`:
https://github.com/hustvl/SparseInst/blob/8e75c646233822ee751253c799eb58226eb5f577/sparseinst/coco_evaluation.py#L24

After adding the same if-condition in my cloned `detectron2`-repo, which your `yolov7` is also relying on, I could train to the end a **SparseInst** on my custom dataset, without getting the missing _pred_boxes_ error anymore. 

So what do you suggest, @jinfagang ? I could send a PR to the `detectron2` people and hope that they may be willing to add this if-condition in their code... I don't see what we can change in our repo otherwise...

**Comment by jinfagang** [comment]
@TeodorChiaburu Hi, here is the solution:

1. create a `yolov7/evaluation/coco_evaluation.py`, which essentially just copy sparseinst's one;
2. then we can export CocoMaskEvaluator in `train_insseg` replace detectron2 one, then everything can just work fine and you should not edit detectron2;
3. last, send me PR.

How about try this?
