### ISSUE TITLE
TypeError: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by paojuzi** [jinfagang/yolov7#12]
when I run " python train_net.py --config-file configs/coco/darknet53.yaml " , the error is as follows:

 TypeError: 'method' object is not subscriptable

the error position is in " yolov7-main\yolov7\modeling\meta_arch\yolo.py ",line 64

I try a lot,but it doesn't work.Can you give me some ideas about it?thanks a lot!

**Comment by Green-Abe** [comment]
The “TypeError: 'method' object is not subscriptable” error is raised when you use square brackets to call a method inside a class. To solve this error, make sure that you only call methods of a class using round brackets after the name of the method you want to call

**Comment by Green-Abe** [comment]
try check brakets inside class

**Comment by paojuzi** [comment]
I tried to change the square brackets into rounds brackets:

self.out0 = self._make_embedding(
            [512, 1024], backbone_shape(-1), out_filter_0)

the new error show up as follows:

TypeError: output_shape() takes 1 positional argument but 2 were given

the source code is:

backbone_shape = self.backbone.output_shape

the function output_shape is defined as follws:

    def output_shape(self):
        """
        Returns:
            dict[str->ShapeSpec]
        """
        # this is a backward-compatible default
        return {
            name: ShapeSpec(
                channels=self._out_feature_channels[name], stride=self._out_feature_strides[name]
            )
            for name in self._out_features
        }

I think the question is that the value of backbone_shape is a dict but the code cannot use index to get the value in it,is that right ?

**Comment by jinfagang** [comment]
@paojuzi Hi, please pull and update. I fixed it.

**Comment by paojuzi** [comment]
@jinfagang I use the newest version of the code which is downald this afternoon,maybe you can just downald it and have a try.Thanks a lot!Addtionally I run the code on windows,I hope it is not caused by the system.
