### ISSUE TITLE
训练实例分割模型时，训练阶段实际未进行，而评估阶段正常进行

### ISSUE THREAD

**Issue by runningcd** [jinfagang/yolov7#123]
如标题所诉：
配置好训练集后，使用如下指令进行训练
python train_custom_datasets.py  --num-gpus 1 --config-file ./configs/coco/sparseinst/sparse_inst_r50vd_giam_aug.yaml MODEL.WEIGHTS weights/sparse_inst_r50vd_giam_aug_8bc5b3.pth SOLVER.BASE_LR 0.001

发现训练阶段打印如下：
![image](https://user-images.githubusercontent.com/45549748/180424004-f1967e3c-d4e8-4030-ba0e-a19830210bf7.png)
GPU使用率为0，经过几个epoch，评估结果未发生明显变化

发现预训练模型分类数量为80与我的训练集分类数量不一致。得到如下提示：
![image](https://user-images.githubusercontent.com/45549748/180424300-c16b35e7-a15d-4c6a-b01e-b2756e3dfebd.png)
于是尝试去掉预训练模型，结果与有预训练模型时一致，实际未进行训练。

请问发生了什么问题？

**Comment by jinfagang** [comment]
I have no idea
