### ISSUE TITLE
AssertionError: Invalid REFERENCE_WORLD_SIZE in config!

### ISSUE THREAD

**Issue by gkpodder** [jinfagang/yolov7#124]
@totoadel I'm getting the same error. I'm trying to image segmentation on colab using the yolov7
File "/content/yolov7/detectron2/detectron2/engine/defaults.py", line 683, in auto_scale_workers
), "Invalid REFERENCE_WORLD_SIZE in config!"
AssertionError: Invalid REFERENCE_WORLD_SIZE in config

Thanks in advance!(sorry for the ping)

**Comment by gkpodder** [comment]
@jinfagang I tried approaching the problem by changing the IMS_PER_BATCH to 1000 and it did stop the error. However, my cuda is now running out of memory. Are there any alternative solutions.

RuntimeError: CUDA out of memory. Tried to allocate 706.00 MiB (GPU 0; 14.76 GiB total capacity; 12.83 GiB already allocated; 479.75 MiB free; 12.86 GiB reserved in total by PyTorch)

**Comment by totoadel** [comment]
@jinfagang use 32 
, 1000 is too high

**Comment by gkpodder** [comment]
@totodel is there any other method to fix it. From my testing, 200 is the lowest before it gives the error but that is still too high for my cuda

**Comment by gkpodder** [comment]
Oh wow nevermind 32 works. How did you arrive at that number I tried many similar ones and it didnt work

**Comment by saprrow** [comment]
> @gkpodder use 32 , 1000 is too high



> Oh wow nevermind 32 works. How did you arrive at that number I tried many similar ones and it didnt work

you can print the `cfg.SOLVER.IMS_PER_BATCH` and `cfg.SOLVER.REFERENCE_WORLD_SIZE`, and make sure that `cfg.SOLVER.IMS_PER_BATCH`   is divisible by `cfg.SOLVER.REFERENCE_WORLD_SIZE`. 
For example, `cfg.SOLVER.IMS_PER_BATC=32` and `cfg.SOLVER.REFERENCE_WORLD_SIZE=8`
