### ISSUE TITLE
export yolomask to onnx error

### ISSUE THREAD

**Issue by mrljwlm** [jinfagang/yolov7#146]
i got the floolwing error when i convert the model to onnx using export.py:

File "I:\yolov7\yolov7\modeling\meta_arch\yolomask.py", line 146, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
IndexError: too many indices for tensor of dimension 3

how can i fix this error? anyone can give me some help?

**Comment by SiChuanJay** [comment]
hello, have you tested the effort of the yolomask model you trained? I trained a yolomask model, but it was bad
