### ISSUE TITLE
自定义coco数据集报错

### ISSUE THREAD

**Issue by AmamiyaRenn** [jinfagang/yolov7#19]
我给train_coco.py加入了如下代码
DATASET_ROOT = './datasets/coco'
ANN_ROOT = os.path.join(DATASET_ROOT, 'annotations')
TRAIN_PATH = os.path.join(DATASET_ROOT, 'train2017')
VAL_PATH = os.path.join(DATASET_ROOT, 'val2017')
TRAIN_JSON = os.path.join(ANN_ROOT, 'instances_train2017.json')
VAL_JSON = os.path.join(ANN_ROOT, 'instances_val2017.json')

register_coco_instances("coco_2017_train", {}, TRAIN_JSON, TRAIN_PATH)
register_coco_instances("coco_2017_val", {}, VAL_JSON, VAL_PATH)

但最后在执行

python train_coco.py --config-file configs/coco/yolox_s.yaml --num-gpus 1

时报错
Install mish-cuda to speed up training and inference. More importantly, replace the naive Mish with MishCuda will give a ~1.5G memory saving during training.
Traceback (most recent call last):
  File "train_coco.py", line 34, in <module>
    register_coco_instances("coco_2017_train", {}, TRAIN_JSON, TRAIN_PATH)
  File "/home/ren/App/Miniconda3/envs/yolov7/lib/python3.7/site-packages/detectron2/data/datasets/coco.py", line 500, in register_coco_instances
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/ren/App/Miniconda3/envs/yolov7/lib/python3.7/site-packages/detectron2/data/catalog.py", line 37, in register
    assert name not in self, "Dataset '{}' is already registered!".format(name)
AssertionError: Dataset 'coco_2017_train' is already registered!

请问这是为什么

**Comment by jinfagang** [comment]
coco is the default dataset registered inside detectron2. Name another dataset name instead.
