### ISSUE TITLE
Coco Map Result?

### ISSUE THREAD

**Issue by kadirnar** [jinfagang/yolov7#2]
How does it perform compared to other yolo models?
What are AP test?  AP50 test ? AP75 test ? Fps?

**Comment by jinfagang** [comment]
@kadirnar yolov7 is not successor of yolo, it just extended yolo into instance segmentation and multi-tasking. For mAP, it even with yolov4 for detection, but it can be higher if using transformer backbone, but speed too slow for this moment. 
If you interested, you can try tweaking on different combination. We also support YOLOX, which is anchor-free version YOLO.

**Comment by kadirnar** [comment]
Thank you for your feedback. Are you considering adding yolov7 to the Detectron2 library? I want to test the yolov7 model with SAHI algorithm.

Demo: https://github.com/obss/sahi/blob/main/demo/inference_for_detectron2.ipynb
Model.py: https://github.com/obss/sahi/blob/main/sahi/model.py#L496+L666

**Comment by jinfagang** [comment]
@kadirnar  YOLOv7 already based on detectron2. You just need copy you model definition file and follow same configuration style in d2 then you can get same result. 
sahi IMO is not a new model, it just slice images into patches and predict one by one. It only useful in certain offline or evaluation scenario.
