### ISSUE TITLE
Performance of defined yolo models

### ISSUE THREAD

**Issue by xignos3108** [jinfagang/yolov7#211]
Hi, I have tried training yolov6_s, cdpdarknet with coco dataset and yolov5_s with VOC dataset however non of them surpassed AP of 10. I know AP of well trained YOLO family for VOC is around 80. I'm having trouble finding the reason for training of the model. What would be the problem?

Here is the result of the training and the environment. Please help me train the model and sorry for the poor English.

- Results
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
| 6.120 | 15.489 | 3.370  | 1.325 | 5.173 | 7.646 | 

- Environment
----------------------  --------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.15 (default, Nov  4 2022, 20:59:55) [GCC 11.2.0]
numpy                   1.23.5
detectron2              0.5 @/home/monet/anaconda3/envs/yolov6/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu101 @/home/monet/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1                 NVIDIA TITAN RTX (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  9.3.0
torchvision             0.9.1+cu101 @/home/monet/anaconda3/envs/yolov6/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20220512
iopath                  0.1.8
cv2                     4.6.0
----------------------  --------------------------------------------------------------------------------------

**Comment by lucasjinreal** [comment]
hello, please using yolox.
