### ISSUE TITLE
SparseInst onnx2trt error

### ISSUE THREAD

**Issue by taxuezcy** [jinfagang/yolov7#24]
@jinfagang ,hello, thank you for your work! when i convert SparseInst onnx model to tensorrt model using trtexec , the error is In node -1(importRange):UNSUPPORTED_NODE:Assertion failed:inputs.at(0).isInt32() && "For range operator with dynamic inputs,this version og TensorRT only supports INT32!
 

tensorrt version:7.2.3
onnx version : v7
pytorch version:1.10

**Comment by jinfagang** [comment]
@taxuezcy Hi, I can not indentify which node caused error, can u attach more detailed error with markdown format, thank u.

**Comment by taxuezcy** [comment]
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] Runner: trt-runner-N0-05/06/22-16:51:11          | Activating and starting inference
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[E] In node -1 (importRange): UNSUPPORTED_NODE: Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
[C] Could not parse ONNX correctly
@jinfagang ，

**Comment by jinfagang** [comment]
@taxuezcy I suggest using onnx-tensorrt to convert rather than txtexec.

this problem should be catched inside onnx-tensorrt.

**Comment by taxuezcy** [comment]
> @taxuezcy I suggest using onnx-tensorrt to convert rather than txtexec.
> 
> this problem should be catched inside onnx-tensorrt. btw, you can also locate which node caused dynamic inputs with int32.

hi,it still can not be solved using onnx-tensorrt, the  error is 
/data_zcy/tools/onnx-tensorrt/build/onnx2trt model_0039999_sim.onnx -o sparse.trt
----------------------------------------------------------------
Input filename:   model_0039999_sim.onnx
ONNX IR version:  0.0.7
Opset version:    13
Producer name:    pytorch
Producer version: 1.10
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2022-05-09 07:42:01 WARNING] onnx2trt_utils.cpp:370: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 205 [Range -> "664"]:
ERROR: builtin_op_importers.cpp:3270 In function importRange:
[8] Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
,i wander how you convert the onnx model to trt? i use the same code ...

**Comment by jinfagang** [comment]
@taxuezcy SparseInst doens't provides a trt version. But I have managed converted to tensorrt int8 engine, but the way should be same except I did some quantization pass.

Your problem seems not alone, you can google a little will found many people have this issue. You can investigate to get a solution.

**Comment by taxuezcy** [comment]
> @taxuezcy SparseInst doens't provides a trt version. But I have managed converted to tensorrt int8 engine, but the way should be same except I did some quantization pass.
> 
> Your problem seems not alone, you can google a little will found many people have this issue. You can investigate to get a solution.

ok, anyway, thank you for your reply, i will try

**Comment by zoufangyu1987** [comment]
I have already resolved it. Upgrade Tensorrt to version TensorRT 8.4 GA Update 1.
我已经解决了。tensorrt升到版本TensorRT 8.4 GA Update 1就可以了。
