### ISSUE TITLE
Exporting the operator linspace to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by caolianxue** [jinfagang/yolov7#25]
您好，根据你的文档说明，我在使用export_onnx,导出模型时，出现上面问题，如何解决？

**Comment by MolianWH** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by jinfagang** [comment]
Just upgrade torch version.

**Comment by MolianWH** [comment]
因为onnx不支持linspace运算，可用arange运算代替。修改yolov7/modeling/transcoders/decoder_sparseinst.py 的122和123行
```
y_loc = torch.arange(-1, 1, 2/h, device=x.device).type(torch.FloatTensor)
x_loc = torch.arange(-1, 1, 2/w, device=x.device).type(torch.FloatTensor)
```
这可能和pytorch版本有关系？如果有人不用修改能成功，请告诉你的pytorch版本。我的是1.8.0

**Comment by MolianWH** [comment]
> Just upgrade torch version.

@jinfagang Could you tell me which version?Thx
