### ISSUE TITLE
sparseinst no results

### ISSUE THREAD

**Issue by MolianWH** [jinfagang/yolov7#26]
I try the demo of sparseinst like this
```python
python demo.py --config-file configs/coco/sparseinst/sparse_inst_r50vd_giam_aug.yaml --video-input ~/Movies/Videos/86277963_nb2-1-80.flv -c 0.4 --opts MODEL.WEIGHTS weights/sparse_inst_r50vd_giam_aug_8bc5b3.pth
```
but I get error
```bash
Traceback (most recent call last):
  File "/home/dreamdeck/Documents/MJJ/code/Seg/yolov7-main/demo.py", line 230, in <module>
    res = vis_res_fast(res, frame, class_names, colors, conf_thresh)
  File "/home/dreamdeck/Documents/MJJ/code/Seg/yolov7-main/demo.py", line 155, in vis_res_fast
    img, clss, bit_masks, force_colors=None, draw_contours=False
  File "/home/dreamdeck/anaconda3/envs/detectron2/lib/python3.6/site-packages/alfred/vis/image/mask.py", line 285, in vis_bitmasks_with_classes
    thickness=-1, lineType=cv2.LINE_AA)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/drawing.cpp:2599: error: (-215:Assertion failed) reader.ptr != NULL in function 'cvDrawContours'
```
I debuged and found that there is no masks when run ` predictions = self.model([inputs])`. All values in `pred_masks` are `False`.

Do I need modify the config file or download other files?( I have dolwnloaded the `sparse_inst_r50vd_giam_aug_8bc5b3.pth`)
What is the full steps to test demo?

**Comment by jinfagang** [comment]
You might need upgrade alfred-py by pip install -U alfred-py

I made a tiny edit on drawing function. The False is the mask value, doesn't means it has not mask. You can print the len of masks instead.

**Comment by MolianWH** [comment]
@jinfagang Thx. I will try it. And I think my environment is not right. Bellow is my env
>pytorch 1.8.0
cuda 10.2
python 3.6

Could you tell me your environment?

**Comment by MolianWH** [comment]
@jinfagang Hi, I update my env. But the error still exist.
I run ` pip install -U alfred-py`, and its version is 2.10.5.
my python version update to 3.9 and pytorch to version 1.10.0.

**Comment by jinfagang** [comment]
OK, I made a quick fix about this. All thought I don't know why..... I tried to checkout back to previous commit, still get your same error. Which is very very strange. Made a quick fix to it:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/21303438/167165764-c5c7a99d-863a-4409-87e3-54c2c45b6790.png">

Just pull the code, you shall fix it.

**Comment by acai66** [comment]
修改alfred源码，再`pip install -e . -U` 安装alfred，可以避免这个bug。
![image](https://user-images.githubusercontent.com/37766207/167381325-b26318c1-4d1c-4174-8b27-ab83957be305.png)

**Comment by jinfagang** [comment]
No need, this was a bug indeed (I still don't know why and I also find SparseInst original author have this issue as well). I have fixed though. Now without changing alfred source code it can also be visualized.
