### ISSUE TITLE
sparseinst pre model results bad

### ISSUE THREAD

**Issue by MolianWH** [jinfagang/yolov7#27]
I test sparseinst series models. Its speed and precision are both terrible.
What reason it may be?
Bellow are some of my results.

many remote class near the hair, and overlapped.

https://user-images.githubusercontent.com/33748947/167154935-cd49f919-531b-4d2e-aa34-a76ecd4c2edc.mp4

![Screenshot from 2022-05-06 22-41-30](https://user-images.githubusercontent.com/33748947/167155784-ebc7c135-ff5d-49ab-9b9a-7e5f0d71cb9f.png)

![Screenshot from 2022-05-06 22-44-21](https://user-images.githubusercontent.com/33748947/167156385-f51500b9-6947-4ef9-ac3c-be492f33f691.png)

**Comment by jinfagang** [comment]
Please set confidence.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/21303438/167166260-46946206-ea36-4f35-83f7-014a3adb98d0.png">

**Comment by MolianWH** [comment]
@jinfagang Thx! it works.
But the sparseInst infer result from demo is not as good as the SparseInst official.

The result from yolov7 demo.py

https://user-images.githubusercontent.com/33748947/168070729-2b51aaad-81d8-4659-a3de-425862180ad9.mp4

The result from official.

https://user-images.githubusercontent.com/33748947/168070934-9b777de0-fb5b-471d-8cfb-cdf6913f3493.mp4
