### ISSUE TITLE
onnxsimplify detr model error

### ISSUE THREAD

**Issue by taxuezcy** [jinfagang/yolov7#36]
@jinfagang ,when sumplify detr onnx model, the error happened,
 onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1682' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2108,1,256}, requested shape:{2108,800,32}
how to solve it?

**Comment by jinfagang** [comment]
I would suggest you read some article someone already managed whole process. Please 百度yolov7 dear

**Comment by taxuezcy** [comment]
> I would suggest you read some article someone already managed whole process. Please 百度yolov7 dear

![image](https://user-images.githubusercontent.com/37206008/168534366-9865c432-df4f-41fe-b115-7a9fea561d0f.png)
确实有yolov7的介绍，但是介绍里面没有写这个报错如何解决的，还请解答一下，谢谢
