### ISSUE TITLE
Inference on SparseInst onnxruntime gives bad output data

### ISSUE THREAD

**Issue by mattiasbax** [jinfagang/yolov7#42]
Hello!

Has anyone successfully exported the sparseinst model to onnx and run inference on it using onnxruntime?
I'm struggling getting reasonable output when running inference in C++ onnxruntime. I'm running the same frame through the network pre-export and the output looks well. But post-export the model outputs scores size (1, 50) with all zeros but a few scores ~0.04. For comparison the model pre-export output two person labels and one sports ball all over 80% confidence. 

I exported the model using the provided export_onnx.py as per readme instruction.
The onnx-model looks, from what I can tell, fine when looking at it Netron.

Just wondering if anyone has successfully used the exported model and could share some examples? =)

**Comment by jinfagang** [comment]
@mattiasbax You shall missed something here:

For onnx exportation, yolov7 will automatically inject -mean / std operation inside model. So there is no need to do any normalization when test on onnxruntime.

Also, don't permute, if your image read with cv2 got like `1, 512, 512, 3,` Just use it into input.

If this can not solve your problem, feel free post someof your result for better debugging.

**Comment by mattiasbax** [comment]
@jinfagang 
Thanks for the response!

Since I need to provide an array of floats to create the input tensor for the onnxruntime session in C++, I do:
* Read image using cv2
* Resize to 640x640
* Flatten to a 640*640*3 cv::Mat (one dimensional image)
* Convert to 32bit float and scaling with a factor of 1/255

I will try to provide some code asap

**Comment by jinfagang** [comment]
@mattiasbax you can contribute your c++ code to `deploy` folder, so that I might help u debug. I am also very welcome contributions helps yolov7 become better and stronger. However, your code license always belongs to u.

**Comment by mattiasbax** [comment]
@jinfagang If i get this to spin correctly I wouldn't mind contributing with some c++ inference examples for the yolov7 repo =)

Pushed the example code to: https://github.com/mattiasbax/sparseinst-cpp-onnxruntime/blob/master/main.cpp
I am printing some session parameters for sanity checking in addition to each of the 1-50 scores + labels. As you can see, the output scores and labels are a bit weird. The same image gave three confident masks of person, person, sportsball. 
If i just input a 0 value tensor I get quite similar but not identical input.

**Running gives output:**
Number of Input Nodes: 1
Input Name 0: images
Input 0 Dimensions: ( -1 640 640 3 )
Number of Output Nodes: 3
Output Name 0: masks
Output 0 Dimensions: ( -1 -1 -1 -1 )
Output Name 1: scores
Output 1 Dimensions: ( 1 50 )
Output Name 2: labels
Output 2 Dimensions: ( 1 50 )
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 13
Data: 0, 0
Data: 0, 13
Data: 0, 0
Data: 0, 0
Data: 0, 74
Data: 0, 0
Data: 0, 13
Data: 0, 0
Data: 0, 0
Data: 0, 13
Data: 0, 13
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 13
Data: 0.0450108, 13
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 14
Data: 0, 0
Data: 0, 0
Data: 0, 25
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 0
Data: 0, 13
Data: 0, 13
Data: 0, 0
Data: 0.0393699, 14
Data: 0, 74
Data: 0, 0
Data: 0, 0
Data: 0, 13
Data: 0, 0
Data: 0.048071, 14
Data: 0.0392799, 0
Data: 0, 0
Data: 0, 0
Data: 0, 14
Data: 0.043646, 13

**Comment by mattiasbax** [comment]
That was it, thanks alot @jinfagang. I will share some C++ example deployment code for the repo if you'd like?

**Comment by jinfagang** [comment]
@mattiasbax don't hesitate send me a PR! I suggest place your code under `deploy` and new a `cc/sparseinst_onnxruntime` folder under there. then PR to main branch I'll merge it. It would be better if you have a readme under your part!
