### ISSUE TITLE
readme need improvements.

### ISSUE THREAD

**Issue by ted8201** [jinfagang/yolov7#48]
Great works. I had just experienced this lib, and running the demo. However, to be honest, the readme is not friendly to users. Concerning the installation instruction, there is too little illustration, almost no requirements illustration. And alfred-py couples with too many third party libs, where no description was provided. For detectron2, the readme for yolov7 requires v0.5, However v0.5 has the problem 
["ImportError: cannot import name '_C'". ](https://detectron2.readthedocs.io/en/latest/tutorials/install.html#:~:text=%22ImportError%3A%20cannot%20import%20name%20%27_C%27%22.)  that needs hacking. All in all, the installation procedure needs too much hacking, without install requirements and installation illustration. Improvements in the readme could may this project more perfect.

**Comment by ted8201** [comment]
> Great works. I had just experienced this lib, and running the demo. However, to be honest, the readme is not friendly to users. Concerning the installation instruction, there is too little illustration, almost no requirements illustration. And alfred-py couples with too many third party libs, where no description was provided. For detectron2, the readme for yolov7 requires v0.5, However v0.5 has the problem ["ImportError: cannot import name '_C'". ](https://detectron2.readthedocs.io/en/latest/tutorials/install.html#:~:text=%22ImportError%3A%20cannot%20import%20name%20%27_C%27%22.) that needs hacking. All in all, the installation procedure needs too much hacking, without install requirements and installation illustration. Improvements in the readme could may this project more perfect.

ps: In my personal opinion, decoupling alfred-py from this project would may it more flexible, concerning alfred-py depends too many 3rdparty libs.

**Comment by jinfagang** [comment]
@ted8201 Can u elebrate why alfred-py depends 3rd party libs bothered you? alfred-py is nothing more than a util lib which helps us more convenient develop models, it doesn't meant to use in deploy.

Does the alfred-py introduce import error on your side? If so, please help me point it out.  

`"ImportError: cannot import name '_C'". ` this has nothing to do with detectron version, it was your installation problem.

**Comment by ted8201** [comment]
**Firstly, and most importantly**, a great project, and I really appreciate it. All I hope is to make it even more great, easy to use for some people like beginners. **Secondly,** when I run alfred in the terminal after installing it using `pip install alfred-py` it will raise exception` no torch` and `no tensorflow`. This means that I must install pytorch and tensorflow both. I hope since I will use only pytorch or tensorflow, not both of them, maybe give me the option to choose one of them instead of install both of them will be better. **Thirdly,** it will complain about opencv-python, matplotlib, lxml, sklearn, pycocotool, etc, should not all this packed with alfred, instead of installing them one by one?  Fourthly, `httpclient_logger = logging.getLogger("http.client")
NameError: name 'logging' is not defined
`. If I install logging using `pip install logging`, it will complain `ERROR: Could not find a version that satisfies the requirement logging (from versions: 0.4.9.6)
ERROR: No matching distribution found for logging
` , which means maybe I have install the wrong version of above packages. Finally, I would say, there is more problems than that I listed here. It's kind of frustrating for nothing, only if we have a better readme.

**Comment by ted8201** [comment]
Wow, never expecting such an quick response. Great Project, Great Works, Great folks.
