### ISSUE TITLE
请问loss_type="v7"的代码在哪里可以看到呢？

### ISSUE THREAD

**Issue by mary-0830** [jinfagang/yolov7#50]
请问loss_type="v7"的代码在哪里可以看到呢？

我看到config里有loss_type有v4,v7这几类，但是没有能够在库里找到相关的代码，请您帮忙解答一下，谢谢。

**Comment by mary-0830** [comment]
我在yolov7.py中找到了loss_type="v7"的代码，请问yolox中在哪里用到了呢？

**Comment by jinfagang** [comment]
this was deprecated. the loss control by arch itself now.
