### ISSUE TITLE
AssertionError: Invalid REFERENCE_WORLD_SIZE in config!

### ISSUE THREAD

**Issue by zkailinzhang** [jinfagang/yolov7#51]
File "//python3.7/site-packages/detectron2/engine/defaults.py", line 674, in auto_scale_workers
    ), "Invalid REFERENCE_WORLD_SIZE in config!"
AssertionError: Invalid REFERENCE_WORLD_SIZE in config!

**Comment by zkailinzhang** [comment]
git clone --branch master

**Comment by totoadel** [comment]
> 

what do you mean by   `git clone --branch master`

**Comment by jinfagang** [comment]
Set `--num_gpus` following physics devices you have.

**Comment by Usama3059** [comment]
AssertionError: Invalid REFERENCE_WORLD_SIZE in config!   getting the same error, I have set the --num_gpus 0 also tried with --num_gpus 1 on colab still same error

**Comment by khakimin** [comment]
> It's working Thanks @totoadel

May I know where do I change the batch size value

**Comment by totoadel** [comment]
@khakimin what config file you are using?

**Comment by gkpodder** [comment]
@totoadel I'm getting the same error. I'm trying to image segmentation on colab using the yolov7
  File "/content/yolov7/detectron2/detectron2/engine/defaults.py", line 683, in auto_scale_workers
    ), "Invalid REFERENCE_WORLD_SIZE in config!"
AssertionError: Invalid REFERENCE_WORLD_SIZE in config

Thanks in advance!

**Comment by totoadel** [comment]
@gkpodder what is the config file you are using
