### ISSUE TITLE
Where can I find the flags list?

### ISSUE THREAD

**Issue by GulerEnes** [jinfagang/yolov7#54]
Hi, I am trying to use your repo to train a model with my custom data but I couldn't find what are the flags of train_visdrone.py. Can you please share documentation on it? 
Also, I couldn't find how to make detection on a set of images.

Regards,

**Comment by jinfagang** [comment]
Please read readme.md first and see docs under docs.

**Comment by GulerEnes** [comment]
Flags not written anywhere? If it's written somewhere please link me there directly.

**Comment by jinfagang** [comment]
If you have trained the model, for inference, just `python demo.py -h` you'll see all flags. details included in readme quick start.
