### ISSUE TITLE
Where is the yolov7 paper?

### ISSUE THREAD

**Issue by Keiku** [jinfagang/yolov7#6]
I think you need to report what kind of research the yolo version has been upgraded to v7, but is there a yolov7 paper? By the way, yolov5 doesn't have a report, so everyone is confused as shown in the link below.

[where is yolov5 paper?](https://github.com/ultralytics/yolov5/issues/1333#)

**Comment by jinfagang** [comment]
@Keiku sorry, yolov7 is just a framework name.

**Comment by Keiku** [comment]
@jinfagang For example, YOLOX and YOLOR are the names of frameworks, but there is also paper properly. If possible, you may want to report a benchmark of what has been upgraded compared to other object detectors.

**Comment by Curt-Park** [comment]
https://github.com/juunini/YOLOv1972
