### ISSUE TITLE
sparseinst onnx result issue

### ISSUE THREAD

**Issue by eremo2002** [jinfagang/yolov7#61]
Hi, thank you for your nice work.

I trained sparseinst and converted onnx model successfully.

But, result is different between pth and onnx. The number of prediction mask is different.

My dataset is single class instance segmentation dataset and all images have 2 instances.
(2 instances per image)

If I inference image using pth in demo.py, I can get correct result. (there are 2 prediction masks)

But, If I inference image using onnx, I get only 1 prediction mask. (mask position is good)

What is problem for difference in the number of masks?

Thank you.

**Comment by jinfagang** [comment]
@eremo2002 You should take a look on scores. Let me know if you give it a further investiation. **this might be a known issue** while I am not sure yet.

**Comment by eremo2002** [comment]
Hi @jinfagang 

you mean prediction scores?

I checked prediction result. But, onnx outputs only 1 prediction.

============================================================
.pth result
============================================================
confidence thresh:  0.5
image after transform:  (512, 512, 3)
cost: 1.585651159286499, fps: 0.6306557366943013
Instances(num_instances=2, image_height=512, image_width=512, fields=[pred_masks: tensor([[[Fal
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]], device='cuda:0'), scores: tensor([0.8287, 0.8166], device='cuda:0'), pred_classes: tensor([0, 0], device='cuda:0')]) [0.82870054 0.81657284] [0 0]




============================================================
onnx result
============================================================
[array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]]]]), array([[0.85961]], dtype=float32), array([[0]], dtype=int64)]

**Comment by jinfagang** [comment]
@eremo2002  try using a lower score threshold in demo_onnx.py, you can change the code for debug.

**Comment by jinfagang** [comment]
config.yaml doesn't effect onnx, onnx doesn't have score thresh, you should handle it inyour onnx inferfence file
