### ISSUE TITLE
When evaluation: Timed out waiting 1800000ms for send operation to complete

### ISSUE THREAD

**Issue by lyumengjin** [jinfagang/yolov7#66]
Every time the program goes into evaluation, the error occurs:

    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 
-- Process 1 terminated with the following error:
File "anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2067, in all_gather
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1646755897462/work/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete

Do u have any idea about it? Thanks a lot.

**Comment by lyumengjin** [comment]
I adapted my batchsize from 32 to 8, this error still occurred...

**Comment by jinfagang** [comment]
I don't have issue on my side. Besides, it's should a detectron2 issue, yolov7 doesn't engaged anything about evaluation.

**Comment by lyumengjin** [comment]
Got it. Thanks for your answer :)
