### ISSUE TITLE
Could you please provide speed and performance benchmark such as yolo-v5?

### ISSUE THREAD

**Issue by Edwardmark** [jinfagang/yolov7#7]
Could you please provide speed and performance benchmark such as yolo-v5?
Thanks.

**Comment by jinfagang** [comment]
Please read readme first. Yolov7 is not successor of yolo series. we just extended yolo to more complicated tasks. Besides, nowadays, you should pay more attention to transformers rather than yolo.

**Comment by Edwardmark** [comment]
@jinfagang I know, I just want to know if yolov7 is better or on par with other detection models. So speed and performance is necessary. Thanks.

**Comment by zyc4me** [comment]
@jinfagang Could you please provide speed and performance benchmark such as yolo-v5?
Thanks.

**Comment by FishHe** [comment]
The authors' contribution is very grateful. However, the speed and performance benchmark can be the most concerned part for developers.
