### ISSUE TITLE
where is output/model_0009999.pth??

### ISSUE THREAD

**Issue by ghzmwhdk777** [jinfagang/yolov7#71]
I ran a successful demo.py using sparse inst weights.

By the way, I would like to check the confidence score and object detection performance. So I checked the issue below and they told me to use the official weight, is it model_0009999.pth that you are talking about? 

All the weights provided seem to be for spareinst. If model_0009999.pth is correct, please let me know if you can provide it, and if not, what other methods can I use to do object detection? (I tried yolov3.pt, but it failed.)

Thank you.

**Comment by afzixhaikh** [comment]
Where is the model? Can you tell me too?
