### ISSUE TITLE
SparseInst export to ONNX input data format

### ISSUE THREAD

**Issue by LukasMahieuArinti** [jinfagang/yolov7#75]
Hi,
I tried exporting the weights of SparseInst (GIAM) that are in this repository to ONNX format using _export.py_ with the following command (I assume I need to use this command? The documentation reads 'use _export_onnx.py_', but there's no _export_onnx.py_ in the current branch of this repository).

`python export.py --config-file configs/coco/sparseinst/sparse_inst_r50_giam_aug.yaml --opts MODEL.WEIGHTS weights/base_giam.pth INPUT.MIN_SIZE_TEST 512`

This leads to the following issue:
```
  File ".../yolov7/yolov7/modeling/meta_arch/sparseinst.py", line 95, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
IndexError: too many indices for tensor of dimension 3
```
Any ideas on how to fix this?
Thank you.

**Comment by jinfagang** [comment]
It was renamed. An onnx file already generated if I am guess it right. Just ignore the error.

**Comment by LukasMahieuArinti** [comment]
I actually want to run the onnx conversion on my custom trained model as well, which is why I'm looking to get the error fixed :/
(Sidenote; I can't download the pretrained SparseInst ONNX file from google drive either, it seems to have been removed)

**Comment by jinfagang** [comment]
onnx is int8 which seems not work at this moment.

**Comment by LukasMahieuArinti** [comment]
Okay, thanks for the reply. I'll try to look for a fix myself then, I'll let you know if I manage to find any.

**Comment by jinfagang** [comment]
the onnx exportation already finished in `torch.onnx.export`, the rest of code is just test onnx inference logic, this is not necessary and definitely could fail. Just ignore..

**Comment by mauricewells** [comment]
Then, how can I test onnx inference logic without the rest of code?

**Comment by ml13571** [comment]
I am asking the same question as mauricewells, as well
Please give me the solution
