### ISSUE TITLE
i have question

### ISSUE THREAD

**Issue by BinParkkk** [jinfagang/yolov7#76]
hi!
Do i can train and detect only bbox ?

my custom dataset has only bbox annotation
i use only that data, so i made json file with bbox (x, y, w, h coordinate) annotation file

but i wander it can train and test .. and how to make result(detect bbox).

i use code with colab

python export.py --config-file configs/coco/darknet53.yaml --input 093816242.jpg --opts MODEL.WEIGHTS model_final.pth

but had error

[07/06 01:16:03 detectron2]: input shape: torch.Size([1, 640, 640, 3])
Traceback (most recent call last):
  File "export.py", line 284, in <module>
    input_names, output_names, dynamic_axes = get_model_infos(args.config_file)
ValueError: not enough values to unpack (expected 3, got 1)

so can you give me a solution about that?

**Comment by jinfagang** [comment]
**READ README FIRST**
