### ISSUE TITLE
AttributeError: 'SparseInst' object has no attribute 'update_iter'

### ISSUE THREAD

**Issue by junho-choi-div** [jinfagang/yolov7#77]
Hello!

I found an error while trying to train the sparseInst model.
I'm using custom data and the command I used is as follows.
python3 train_custom_datasets.py --config-file /content/yolov7/configs/coco/sparseinst/sparse_inst_r50vd_dcn_giam_aug.yaml --num-gpus 1

![image](https://user-images.githubusercontent.com/88411307/177685129-a86d2fa2-a57a-4402-a331-0c368eb9360e.png)

Can I know where 'update_iter' is defined? or How can I fix this error? 

Thanks!

**Comment by jinfagang** [comment]
Please comment out `def run_step`, it was using matching with mosaic augmentation, as instance not use it, you can comment it out.

**Comment by TeodorChiaburu** [comment]
I ran into the same problem when trying to train a SparseInst on my own dataset. Commenting out `def run_step` removed the error. Is it planned to rewrite the `run_step` function in the near future or should we submit a PR where the function is removed? Thank you!

**Comment by jinfagang** [comment]
yes, PR are very welcomed!
